version: "3"
services:
  prediction-service:
    build: ./apps/prediction-service
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - SERVER_PORT=3000
      - ML_SERVICE_HOST=ml-service
      - ML_SERVICE_PORT=3001
      - RABBITMQ_USER=user
      - RABBITMQ_PASSWORD=password
      - RABBITMQ_HOST=rabbitmq
      - ALARMS_API_KEY=888fbe4f:425a89be3ec0c27b8f4f61218b18ef4d
    depends_on:
      - ml-service
      - rabbitmq
  ml-service:
    build: ./apps/ml-service
    ports:
      - "3001:3001"
    environment:
      - SERVER_PORT=3000
      - ML_SERVICE_HOST=ml-service
      - ML_SERVICE_PORT=3001
      - RABBITMQ_USER=user
      - RABBITMQ_PASSWORD=password
      - RABBITMQ_HOST=rabbitmq
    restart: unless-stopped
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"  # RabbitMQ default port for AMQP
      - "15672:15672"  # RabbitMQ management console port
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Persist RabbitMQ data
volumes:
  rabbitmq_data: